In [21]:
import numpy as np
import pandas as pd

In [22]:
train=pd.read_table("hw6_adaboost_train.dat",delim_whitespace=True,header=None)
train

           0         1  2
0   0.757222  0.633831 -1
1   0.847382  0.281581 -1
2   0.249310  0.618635  1
3   0.538526  0.144259 -1
4   0.474435  0.414558 -1
5   0.374151  0.012048  1
6   0.847185  0.217572  1
7   0.983368  0.250496  1
8   0.645141  0.485816  1
9   0.172211  0.254331 -1
10  0.116866  0.378804 -1
11  0.550970  0.760426 -1
12  0.312109  0.442938 -1
13  0.304777  0.052965  1
14  0.572727  0.370527  1
15  0.171491  0.500760 -1
16  0.644567  0.834055 -1
17  0.052904  0.338461 -1
18  0.032354  0.830701 -1
19  0.272193  0.587396 -1
20  0.123521  0.051663  1
21  0.905544  0.247013  1
22  0.854276  0.559648  1
23  0.375914  0.505747 -1
24  0.160755  0.238718 -1
25  0.458930  0.227062  1
26  0.395407  0.791184 -1
27  0.742325  0.586444  1
28  0.436150  0.136922  1
29  0.954217  0.680325  1
..       ...       ... ..
70  0.901988  0.831265  1
71  0.692314  0.064043  1
72  0.836977  0.614453  1
73  0.104584  0.357892 -1
74  0.265266  0.658330 -1
75  0.729254  0.885763 -1
76  0.205254  0.404956 -1
77  0.032359  0.778401 -1
78  0.464724  0.159682  1
79  0.940021  0.493738  1
80  0.248985  0.646083 -1
81  0.541258  0.728218 -1
82  0.391575  0.291076  1
83  0.025497  0.300503 -1
84  0.475398  0.920203 -1
85  0.835664  0.584283  1
86  0.296033  0.088516  1
87  0.043591  0.646312 -1
88  0.284148  0.182427  1
89  0.627696  0.788116 -1
90  0.312939  0.871275 -1
91  0.676521  0.316903  1
92  0.012354  0.178643 -1
93  0.682164  0.777194 -1
94  0.421563  0.302683  1
95  0.031830  0.289761 -1
96  0.435715  0.190071  1
97  0.730492  0.065559  1
98  0.925270  0.524315  1
99  0.984815  0.383621  1

[100 rows x 3 columns]

In [23]:
test=pd.read_table("hw6_adaboost_test.dat",delim_whitespace=True,header=None)
test

            0         1  2
0    0.984250  0.712610 -1
1    0.901491  0.462824 -1
2    0.872418  0.365547 -1
3    0.810913  0.058338 -1
4    0.577230  0.203007 -1
5    0.397929  0.566680  1
6    0.120766  0.440112  1
7    0.621890  0.905915  1
8    0.870767  0.053475 -1
9    0.260869  0.471334  1
10   0.848156  0.510922 -1
11   0.067217  0.177358  1
12   0.359852  0.563900  1
13   0.254761  0.864500  1
14   0.145275  0.238116  1
15   0.649450  0.147829 -1
16   0.350556  0.058309 -1
17   0.961156  0.628020 -1
18   0.523740  0.017673 -1
19   0.751678  0.276548 -1
20   0.012118  0.975133  1
21   0.575086  0.776408  1
22   0.597629  0.231500 -1
23   0.817010  0.648010 -1
24   0.672220  0.130962 -1
25   0.884317  0.598321 -1
26   0.907254  0.814164 -1
27   0.144621  0.904808  1
28   0.182951  0.380950  1
29   0.801427  0.461995 -1
..        ...       ... ..
970  0.121895  0.622460 -1
971  0.938497  0.175046  1
972  0.309569  0.187634  1
973  0.945545  0.818893  1
974  0.656243  0.119367  1
975  0.878904  0.613301  1
976  0.348720  0.465452 -1
977  0.224392  0.631975 -1
978  0.177952  0.750608 -1
979  0.568367  0.288115  1
980  0.292361  0.040819  1
981  0.290532  0.843732 -1
982  0.014771  0.400843 -1
983  0.558114  0.678272 -1
984  0.964430  0.850934  1
985  0.857355  0.260394  1
986  0.007543  0.998004 -1
987  0.602324  0.842636 -1
988  0.341327  0.801777 -1
989  0.108357  0.673782 -1
990  0.513777  0.566489 -1
991  0.445600  0.367347  1
992  0.491244  0.831120 -1
993  0.891817  0.565568  1
994  0.141926  0.792559 -1
995  0.412943  0.988291 -1
996  0.056087  0.798841 -1
997  0.361979  0.860275 -1
998  0.736251  0.461332  1
999  0.090363  0.880068 -1

[1000 rows x 3 columns]

In [24]:
train.columns

Int64Index([0, 1, 2], dtype='int64')

In [25]:
len(train.columns)

3

In [26]:
for i in range(len(train.columns)-1):
    print (i)

0
1

In [27]:
train.sort_values(by=[0])

           0         1  2
92  0.012354  0.178643 -1
83  0.025497  0.300503 -1
95  0.031830  0.289761 -1
18  0.032354  0.830701 -1
77  0.032359  0.778401 -1
87  0.043591  0.646312 -1
17  0.052904  0.338461 -1
41  0.074802  0.568699 -1
73  0.104584  0.357892 -1
10  0.116866  0.378804 -1
20  0.123521  0.051663  1
36  0.124333  0.611515 -1
60  0.145192  0.377728 -1
52  0.158561  0.690295 -1
24  0.160755  0.238718 -1
15  0.171491  0.500760 -1
9   0.172211  0.254331 -1
40  0.204973  0.406648 -1
76  0.205254  0.404956 -1
49  0.243625  0.106277  1
80  0.248985  0.646083 -1
2   0.249310  0.618635  1
35  0.249529  0.070908  1
74  0.265266  0.658330 -1
19  0.272193  0.587396 -1
33  0.275732  0.431150 -1
88  0.284148  0.182427  1
86  0.296033  0.088516  1
62  0.296852  0.868018 -1
13  0.304777  0.052965  1
..       ...       ... ..
58  0.696778  0.300018  1
48  0.708026  0.300654  1
51  0.726241  0.057674  1
75  0.729254  0.885763 -1
97  0.730492  0.065559  1
27  0.742325  0.586444  1
0   0.757222  0.633831 -1
46  0.802581  0.599025  1
66  0.815532  0.164151  1
85  0.835664  0.584283  1
72  0.836977  0.614453  1
6   0.847185  0.217572  1
1   0.847382  0.281581 -1
22  0.854276  0.559648  1
38  0.860190  0.930290 -1
34  0.892366  0.013666  1
64  0.896153  0.832046  1
70  0.901988  0.831265  1
21  0.905544  0.247013  1
30  0.916386  0.381431  1
98  0.925270  0.524315  1
59  0.927038  0.295737  1
55  0.933469  0.490516  1
42  0.936407  0.106094  1
79  0.940021  0.493738  1
31  0.953844  0.439266  1
29  0.954217  0.680325  1
50  0.960778  0.597990  1
7   0.983368  0.250496  1
99  0.984815  0.383621  1

[100 rows x 3 columns]

In [29]:
train_test=train.sort_values(by=[0])[0]
train_test

92    0.012354
83    0.025497
95    0.031830
18    0.032354
77    0.032359
87    0.043591
17    0.052904
41    0.074802
73    0.104584
10    0.116866
20    0.123521
36    0.124333
60    0.145192
52    0.158561
24    0.160755
15    0.171491
9     0.172211
40    0.204973
76    0.205254
49    0.243625
80    0.248985
2     0.249310
35    0.249529
74    0.265266
19    0.272193
33    0.275732
88    0.284148
86    0.296033
62    0.296852
13    0.304777
        ...
58    0.696778
48    0.708026
51    0.726241
75    0.729254
97    0.730492
27    0.742325
0     0.757222
46    0.802581
66    0.815532
85    0.835664
72    0.836977
6     0.847185
1     0.847382
22    0.854276
38    0.860190
34    0.892366
64    0.896153
70    0.901988
21    0.905544
30    0.916386
98    0.925270
59    0.927038
55    0.933469
42    0.936407
79    0.940021
31    0.953844
29    0.954217
50    0.960778
7     0.983368
99    0.984815
Name: 0, Length: 100, dtype: float64

In [30]:
train_test=train_test.reset_index(drop=True)
train_test

0     0.012354
1     0.025497
2     0.031830
3     0.032354
4     0.032359
5     0.043591
6     0.052904
7     0.074802
8     0.104584
9     0.116866
10    0.123521
11    0.124333
12    0.145192
13    0.158561
14    0.160755
15    0.171491
16    0.172211
17    0.204973
18    0.205254
19    0.243625
20    0.248985
21    0.249310
22    0.249529
23    0.265266
24    0.272193
25    0.275732
26    0.284148
27    0.296033
28    0.296852
29    0.304777
        ...
70    0.696778
71    0.708026
72    0.726241
73    0.729254
74    0.730492
75    0.742325
76    0.757222
77    0.802581
78    0.815532
79    0.835664
80    0.836977
81    0.847185
82    0.847382
83    0.854276
84    0.860190
85    0.892366
86    0.896153
87    0.901988
88    0.905544
89    0.916386
90    0.925270
91    0.927038
92    0.933469
93    0.936407
94    0.940021
95    0.953844
96    0.954217
97    0.960778
98    0.983368
99    0.984815
Name: 0, Length: 100, dtype: float64

In [31]:
train_test[0]

0.012353900000000001

In [32]:
len(train_test)

100

In [33]:
theta=[(train_test[i]+train_test[i+1])/2 for i in range(len(train_test)-2)] 
theta

[0.018925299999999999,
 0.028663350000000004,
 0.03209215,
 0.032356650000000001,
 0.037974899999999999,
 0.048247449999999997,
 0.063853300000000002,
 0.089693250000000002,
 0.110725,
 0.12019350000000001,
 0.12392700000000001,
 0.13476250000000001,
 0.1518765,
 0.15965799999999999,
 0.16612300000000002,
 0.171851,
 0.18859199999999998,
 0.2051135,
 0.22443950000000001,
 0.246305,
 0.24914749999999999,
 0.24941950000000002,
 0.2573975,
 0.26872949999999995,
 0.2739625,
 0.27994000000000002,
 0.29009050000000003,
 0.2964425,
 0.30081449999999998,
 0.30744700000000003,
 0.31111300000000003,
 0.31252400000000002,
 0.32081999999999999,
 0.34365950000000001,
 0.36271799999999998,
 0.36808149999999995,
 0.37174799999999997,
 0.37503249999999999,
 0.38067449999999997,
 0.38850499999999999,
 0.39349100000000004,
 0.40802250000000001,
 0.42110049999999999,
 0.42698350000000002,
 0.43405949999999999,
 0.43593249999999995,
 0.44753999999999999,
 0.46182699999999999,
 0.46543049999999997,
 0.47028599999999998,
 0.47491649999999996,
 0.48913099999999998,
 0.51262450000000004,
 0.53045549999999997,
 0.53989200000000004,
 0.54287399999999997,
 0.54772999999999994,
 0.56184849999999997,
 0.57272750000000006,
 0.58393950000000006,
 0.61142350000000001,
 0.62969050000000004,
 0.63812599999999997,
 0.64485400000000004,
 0.64824249999999994,
 0.65527399999999991,
 0.66786250000000003,
 0.67934249999999996,
 0.68723899999999993,
 0.694546,
 0.70240199999999997,
 0.71713350000000009,
 0.72774749999999999,
 0.72987299999999999,
 0.73640850000000002,
 0.74977350000000009,
 0.77990150000000003,
 0.80905649999999996,
 0.82559799999999994,
 0.83632050000000002,
 0.84208100000000008,
 0.84728350000000008,
 0.85082900000000006,
 0.85723300000000002,
 0.876278,
 0.89425949999999998,
 0.89907049999999999,
 0.90376599999999996,
 0.91096500000000002,
 0.92082799999999998,
 0.92615399999999992,
 0.93025350000000007,
 0.93493800000000005,
 0.93821399999999988,
 0.94693249999999995,
 0.9540305,
 0.9574975,
 0.97207299999999996]

In [34]:
train_test_Y=train.sort_values(by=[0])[2]
train_test_Y

92   -1
83   -1
95   -1
18   -1
77   -1
87   -1
17   -1
41   -1
73   -1
10   -1
20    1
36   -1
60   -1
52   -1
24   -1
15   -1
9    -1
40   -1
76   -1
49    1
80   -1
2     1
35    1
74   -1
19   -1
33   -1
88    1
86    1
62   -1
13    1
     ..
58    1
48    1
51    1
75   -1
97    1
27    1
0    -1
46    1
66    1
85    1
72    1
6     1
1    -1
22    1
38   -1
34    1
64    1
70    1
21    1
30    1
98    1
59    1
55    1
42    1
79    1
31    1
29    1
50    1
7     1
99    1
Name: 2, Length: 100, dtype: int64

In [35]:
theta[0]

0.018925299999999999

In [36]:
s=1
def sign(x):
    return (x>0)*2-1
result=s*sign(train_test-theta[0])
result

0    -1
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    1
16    1
17    1
18    1
19    1
20    1
21    1
22    1
23    1
24    1
25    1
26    1
27    1
28    1
29    1
     ..
70    1
71    1
72    1
73    1
74    1
75    1
76    1
77    1
78    1
79    1
80    1
81    1
82    1
83    1
84    1
85    1
86    1
87    1
88    1
89    1
90    1
91    1
92    1
93    1
94    1
95    1
96    1
97    1
98    1
99    1
Name: 0, Length: 100, dtype: int32

In [43]:
pd.DataFrame(result)==pd.DataFrame(train_test_Y)

    0
0  -1
1   1
2   1
3   1
4   1
5   1
6   1
7   1
8   1
9   1
10  1
11  1
12  1
13  1
14  1
15  1
16  1
17  1
18  1
19  1
20  1
21  1
22  1
23  1
24  1
25  1
26  1
27  1
28  1
29  1
.. ..
70  1
71  1
72  1
73  1
74  1
75  1
76  1
77  1
78  1
79  1
80  1
81  1
82  1
83  1
84  1
85  1
86  1
87  1
88  1
89  1
90  1
91  1
92  1
93  1
94  1
95  1
96  1
97  1
98  1
99  1

[100 rows x 1 columns]